// Ada crew sprites — 16x16 bitmaps.
// Generated from the design file; every sprite is verified 16 rows x 16 chars.
// '.' = transparent. Any other char indexes that sprite's palette.
// DO NOT hand-edit rows: a row that is not exactly 16 chars will render skewed.

export type Sprite = { palette: Record<string, string>; rows: string[] };

export const SPRITES: Record<string, Sprite> = {
  astronaut: {
    palette: {"d":"#0F1113","w":"#E6E9ED","v":"#F0A733","h":"#FFD98A"},
    rows: [
      "................",
      "....dddddddd....",
      "..ddwwwwwwwwdd..",
      ".ddwwwwwwwwwwdd.",
      ".dwwvvvvvvvvwwd.",
      ".dwvvvvhhvvvvwd.",
      ".dwvvvvvvvvvvwd.",
      ".dwvvvvvvvvvvwd.",
      ".dwwvvvvvvvvwwd.",
      ".ddwwwwwwwwwwdd.",
      "..ddwwwwwwwwdd..",
      "....ddwwwwdd....",
      "...dwwwwwwwwd...",
      "..dwwwwwwwwwwd..",
      "..dwwwddddwwwd..",
      "..dwwd....dwwd..",
    ],
  },
  alien: {
    palette: {"g":"#8FD94A","k":"#0B0D0E"},
    rows: [
      "................",
      "....gggggggg....",
      "..gggggggggggg..",
      ".gggggggggggggg.",
      ".gggggggggggggg.",
      ".ggkkkkggkkkkgg.",
      ".gkkkkggggkkkkg.",
      ".ggkkkkggkkkkgg.",
      "..gggggggggggg..",
      "..gggggggggggg..",
      "...gggggggggg...",
      "....gggggggg....",
      ".....gggggg.....",
      "......gggg......",
      ".....g.gg.g.....",
      "................",
    ],
  },
  robot: {
    palette: {"d":"#0F1113","s":"#B8BFC7","c":"#22262A","b":"#5AA9F0"},
    rows: [
      "................",
      ".......dd.......",
      "......dbbd......",
      "....dddddddd....",
      "...dssssssssd...",
      "..dssssssssssd..",
      "..dscccccccccd..",
      "..dscbbcccbbcd..",
      "..dscbbcccbbcd..",
      "..dscccccccccd..",
      "..dssssssssssd..",
      "...dssssssssd...",
      "....dddddddd....",
      ".....dssssd.....",
      "....dssssssd....",
      "....d.d..d.d....",
    ],
  },
  pirate: {
    palette: {"d":"#0F1113","h":"#22262A","w":"#E6E9ED","f":"#E0A87A","k":"#0B0D0E","p":"#0B0D0E","b":"#6B4A2F"},
    rows: [
      "................",
      "...dddddddddd...",
      "..dhhhhhhhhhhd..",
      "..dhhhhwwhhhhd..",
      "..dhhhwwwwhhhd..",
      "...dhhhhhhhhd...",
      "..dddddddddddd..",
      "..dffffffffffd..",
      "..dfkkfffppffd..",
      "..dffffffffffd..",
      "..dfffdddffffd..",
      "..dbbbbbbbbbbd..",
      "...dbbbbbbbbd...",
      "....dbbbbbbd....",
      ".....dbbbbd.....",
      "................",
    ],
  },
  ghost: {
    palette: {"d":"#2A3038","w":"#D6DCE4","k":"#0B0D0E"},
    rows: [
      "................",
      ".....dddddd.....",
      "...ddwwwwwwdd...",
      "..dwwwwwwwwwwd..",
      ".dwwwwwwwwwwwwd.",
      ".dwwkkwwwwkkwwd.",
      ".dwwkkwwwwkkwwd.",
      ".dwwwwwwwwwwwwd.",
      ".dwwwwwwwwwwwwd.",
      ".dwwwwwwwwwwwwd.",
      ".dwwwwwwwwwwwwd.",
      ".dwwwwwwwwwwwwd.",
      ".dwwdwwddwwdwwd.",
      ".dwd..dwd..dwwd.",
      "................",
      "................",
    ],
  },
  detective: {
    palette: {"d":"#0F1113","h":"#3A4046","f":"#E0A87A","k":"#0B0D0E","c":"#4A5058"},
    rows: [
      "................",
      "................",
      "...dddddddddd...",
      "..dhhhhhhhhhhd..",
      "..dhhhhhhhhhhd..",
      ".dddddddddddddd.",
      "..dffffffffffd..",
      "..dffffffffffd..",
      "..dfkkffffkkfd..",
      "..dffffffffffd..",
      "..dfffdddffffd..",
      "..dffffffffffd..",
      "...dffffffffd...",
      "....dddddddd....",
      "..dcccccccccd...",
      "..dcccccccccd...",
    ],
  },
  scribe: {
    palette: {"d":"#0F1113","r":"#6B5A8A","f":"#E0A87A","k":"#0B0D0E"},
    rows: [
      "................",
      ".....dddddd.....",
      "...ddrrrrrrdd...",
      "..drrrrrrrrrrd..",
      "..drrddddddrrd..",
      "..drdffffffdrd..",
      "..drdfkffkfdrd..",
      "..drdffffffdrd..",
      "..drdffffffdrd..",
      "..drddffffddrd..",
      "..drrrddddrrrd..",
      "..drrrrrrrrrrd..",
      "..drrrrrrrrrrd..",
      "...drrrrrrrrd...",
      "...drrrrrrrrd...",
      "................",
    ],
  },
  pilot: {
    palette: {"d":"#0F1113","c":"#7A5C3A","g":"#C9A227","k":"#0B0D0E","f":"#E0A87A","j":"#C4655E"},
    rows: [
      "................",
      "....dddddddd....",
      "..ddccccccccdd..",
      ".dccccccccccccd.",
      ".dccccccccccccd.",
      ".dcggggddggggcd.",
      ".dcgkkgddgkkgcd.",
      ".dcggggddggggcd.",
      ".dcffffffffffcd.",
      ".dcffffffffffcd.",
      ".dcfffddddfffcd.",
      ".dcffffffffffcd.",
      ".dccdffffffdccd.",
      ".dccd......dccd.",
      "..dcd......dcd..",
      "................",
    ],
  },
  commander: {
    palette: {"d":"#0F1113","h":"#3A2A22","f":"#E0A87A","k":"#0B0D0E","u":"#2E4A6B","a":"#F0A733"},
    rows: [
      "................",
      "................",
      ".....dddddd.....",
      "....dhhhhhhd....",
      "...dhhhhhhhhd...",
      "...dhffffffhd...",
      "...dffffffffd...",
      "...dfkkffkkfd...",
      "...dffffffffd...",
      "...dffddddffd...",
      "....dffffffd....",
      ".....dddddd.....",
      "...dduuuuuudd...",
      "..duuuuaauuuud..",
      ".duuuuuaauuuuud.",
      ".duuuuuuuuuuuud.",
    ],
  },
  comms: {
    palette: {"d":"#0F1113","h":"#16181B","f":"#C98A5E","k":"#0B0D0E","g":"#3FD2C7","m":"#3FD2C7","u":"#1F5A57"},
    rows: [
      "................",
      ".....dddddd.....",
      "...ddhhhhhhdd...",
      "..dhhhhhhhhhhd..",
      "dgdhhhhhhhhhhdgd",
      "dggdhhhhhhhhdggd",
      "dggdffffffffdggd",
      "dggdfkkffkkfdggd",
      "dggdffffffffdggd",
      "dgdmffdddfffdgd.",
      "...mffffffffd...",
      "...dffffffffd...",
      "....dddddddd....",
      "..dduuuuuuuudd..",
      ".duuuuuuuuuuuud.",
      ".duuuuuuuuuuuud.",
    ],
  },
  engineer: {
    palette: {"d":"#0F1113","c":"#C9722A","v":"#F0A733","f":"#E0A87A","k":"#0B0D0E","s":"#5A4A3A","o":"#C9722A"},
    rows: [
      "................",
      "......dddd......",
      ".....dccccd.....",
      "....dccccccd....",
      "dddccccccccccddd",
      "dccccccccccccccd",
      "..dddddddddddd..",
      "..dvvvvvvvvvvd..",
      "..dffffffffffd..",
      "..dfkkffffkkfd..",
      "..dffffffffffd..",
      "..dsssddddsssd..",
      "...dssssssssd...",
      "....dddddddd....",
      "..ddoooooooodd..",
      ".dooooooooooood.",
    ],
  },
  medic: {
    palette: {"d":"#0F1113","w":"#E6E9ED","r":"#E8635B","f":"#E0A87A","k":"#0B0D0E","l":"#FFE9A8"},
    rows: [
      "................",
      "................",
      "....dddddddd....",
      "...dwwwwwwwwd...",
      "...dwwlllwwwd...",
      "...dddddddddd...",
      "....dffffffd....",
      "....dfkffkfd....",
      "....dffffffd....",
      "....dfddddfd....",
      ".....dffffd.....",
      "....dddddddd....",
      "..dwwwwwwwwwwd..",
      ".dwwwwwrrwwwwwd.",
      ".dwwwwrrrrwwwwd.",
      ".dwwwwwrrwwwwwd.",
    ],
  },
  probe: {
    palette: {"d":"#0F1113","p":"#2E4A6B","s":"#B8BFC7","c":"#22262A","b":"#5AA9F0"},
    rows: [
      "................",
      "................",
      ".......dd.......",
      "......dbbd......",
      "....dddddddd....",
      "dpddssssssssddpd",
      "dpddsccccccsddpd",
      "dpddscbbbbcsddpd",
      "dpddsccccccsddpd",
      "dpddssssssssddpd",
      "....dddddddd....",
      ".....dssssd.....",
      "......dssd......",
      "................",
      "................",
      "................",
    ],
  },
};

export type SpriteName = keyof typeof SPRITES;

/** The nine crewed stations, in roster order. Ada is mission control and uses the
 *  existing punch-card `PunchA` mark instead of a sprite. */
export const CREW = [
  { sprite: "commander", name: "Commander", role: "Planner" },
  { sprite: "astronaut", name: "Scout", role: "Researcher" },
  { sprite: "comms", name: "Comms", role: "Writer" },
  { sprite: "robot", name: "Android", role: "Summarizer" },
  { sprite: "engineer", name: "Engineer", role: "Fetcher" },
  { sprite: "medic", name: "Medic", role: "Verifier" },
  { sprite: "pilot", name: "Navigator", role: "Router" },
  { sprite: "probe", name: "Probe", role: "Monitor" },
] as const;

/** Drawn but unassigned. Use for user-created agents. */
export const BENCH = [
  { sprite: "alien", name: "Xeno" },
  { sprite: "ghost", name: "Ghost" },
  { sprite: "pirate", name: "Privateer" },
  { sprite: "scribe", name: "Archivist" },
  { sprite: "detective", name: "Inspector" },
] as const;
